package net.ccbluex.liquidbounce.features.module.modules.test

import net.ccbluex.liquidbounce.event.PacketEvent
import net.ccbluex.liquidbounce.event.UpdateEvent
import net.ccbluex.liquidbounce.event.handler
import net.ccbluex.liquidbounce.features.module.Category
import net.ccbluex.liquidbounce.features.module.Module
import net.ccbluex.liquidbounce.utils.client.PacketUtils.sendPacket
import net.minecraft.network.handshake.client.C00Handshake
import net.minecraft.network.login.client.C00PacketLoginStart
import net.minecraft.network.login.client.C01PacketEncryptionResponse
import net.minecraft.network.login.server.S00PacketDisconnect
import net.minecraft.network.login.server.S01PacketEncryptionRequest
import net.minecraft.network.login.server.S02PacketLoginSuccess
import net.minecraft.network.login.server.S03PacketEnableCompression
import net.minecraft.network.play.client.*
import net.minecraft.network.play.server.*
import net.minecraft.network.status.client.C00PacketServerQuery
import net.minecraft.network.status.client.C01PacketPing
import net.minecraft.network.status.server.S00PacketServerInfo
import net.minecraft.network.status.server.S01PacketPong

object PacketManager : Module("PacketManager", Category.TEST) {
    // 登录协议包 (客户端)
    val ControlC00PacketLoginStart by choices("C00PacketLoginStart", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC01PacketEncryptionResponse by choices("C01PacketEncryptionResponse", arrayOf("NoControl","Send","Cancel"), "NoControl")

    // 状态协议包 (客户端)
    val ControlC00PacketServerQuery by choices("C00PacketServerQuery", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC01PacketPing by choices("C01PacketPing", arrayOf("NoControl","Send","Cancel"), "NoControl")

    // 游戏协议包 (客户端)
    val ControlC00PacketKeepAlive by choices("C00PacketKeepAlive", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC01PacketChatMessage by choices("C01PacketChatMessage", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC02PacketUseEntity by choices("C02PacketUseEntity", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC03PacketPlayer by choices("C03PacketPlayer", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC04PacketPlayerPosition by choices("C04PacketPlayerPosition", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC05PacketPlayerLook by choices("C05PacketPlayerLook", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC06PacketPlayerPosLook by choices("C06PacketPlayerPosLook", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC07PacketPlayerDigging by choices("C07PacketPlayerDigging", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC08PacketPlayerBlockPlacement by choices("C08PacketPlayerBlockPlacement", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC09PacketHeldItemChange by choices("C09PacketHeldItemChange", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC0APacketAnimation by choices("C0APacketAnimation", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC0BPacketEntityAction by choices("C0BPacketEntityAction", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC0CPacketInput by choices("C0CPacketInput", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC0DPacketCloseWindow by choices("C0DPacketCloseWindow", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC0EPacketClickWindow by choices("C0EPacketClickWindow", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC0FPacketConfirmTransaction by choices("C0FPacketConfirmTransaction", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC10PacketCreativeInventoryAction by choices("C10PacketCreativeInventoryAction", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC11PacketEnchantItem by choices("C11PacketEnchantItem", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC12PacketUpdateSign by choices("C12PacketUpdateSign", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC13PacketPlayerAbilities by choices("C13PacketPlayerAbilities", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC14PacketTabComplete by choices("C14PacketTabComplete", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC15PacketClientSettings by choices("C15PacketClientSettings", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC16PacketClientStatus by choices("C16PacketClientStatus", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC17PacketCustomPayload by choices("C17PacketCustomPayload", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC18PacketSpectate by choices("C18PacketSpectate", arrayOf("NoControl","Send","Cancel"), "NoControl")
    val ControlC19PacketResourcePackStatus by choices("C19PacketResourcePackStatus", arrayOf("NoControl","Send","Cancel"), "NoControl")

    // 握手协议包 (客户端)
    val ControlC00Handshake by choices("C00Handshake", arrayOf("NoControl","Send","Cancel"), "NoControl")

    // 登录协议包 (服务端)
    val ControlS00PacketDisconnect by choices("S00PacketDisconnect", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS01PacketEncryptionRequest by choices("S01PacketEncryptionRequest", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS02PacketLoginSuccess by choices("S02PacketLoginSuccess", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS03PacketEnableCompression by choices("S03PacketEnableCompression", arrayOf("NoControl","Cancel"), "NoControl")

    // 状态协议包 (服务端)
    val ControlS00PacketServerInfo by choices("S00PacketServerInfo", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS01PacketPong by choices("S01PacketPong", arrayOf("NoControl","Cancel"), "NoControl")

    // 游戏协议包 (服务端)
    val ControlS00PacketKeepAlive by choices("S00PacketKeepAlive", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS01PacketJoinGame by choices("S01PacketJoinGame", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS02PacketChat by choices("S02PacketChat", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS03PacketTimeUpdate by choices("S03PacketTimeUpdate", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS04PacketEntityEquipment by choices("S04PacketEntityEquipment", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS05PacketSpawnPosition by choices("S05PacketSpawnPosition", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS06PacketUpdateHealth by choices("S06PacketUpdateHealth", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS07PacketRespawn by choices("S07PacketRespawn", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS08PacketPlayerPosLook by choices("S08PacketPlayerPosLook", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS09PacketHeldItemChange by choices("S09PacketHeldItemChange", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS0APacketUseBed by choices("S0APacketUseBed", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS0BPacketAnimation by choices("S0BPacketAnimation", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS0CPacketSpawnPlayer by choices("S0CPacketSpawnPlayer", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS0DPacketCollectItem by choices("S0DPacketCollectItem", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS0EPacketSpawnObject by choices("S0EPacketSpawnObject", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS0FPacketSpawnMob by choices("S0FPacketSpawnMob", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS10PacketSpawnPainting by choices("S10PacketSpawnPainting", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS11PacketSpawnExperienceOrb by choices("S11PacketSpawnExperienceOrb", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS12PacketEntityVelocity by choices("S12PacketEntityVelocity", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS13PacketDestroyEntities by choices("S13PacketDestroyEntities", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS14PacketEntity by choices("S14PacketEntity", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS18PacketEntityTeleport by choices("S18PacketEntityTeleport", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS19PacketEntityHeadLook by choices("S19PacketEntityHeadLook", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS19PacketEntityStatus by choices("S19PacketEntityStatus", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS1BPacketEntityAttach by choices("S1BPacketEntityAttach", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS1CPacketEntityMetadata by choices("S1CPacketEntityMetadata", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS1DPacketEntityEffect by choices("S1DPacketEntityEffect", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS1EPacketRemoveEntityEffect by choices("S1EPacketRemoveEntityEffect", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS1FPacketSetExperience by choices("S1FPacketSetExperience", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS20PacketEntityProperties by choices("S20PacketEntityProperties", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS21PacketChunkData by choices("S21PacketChunkData", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS22PacketMultiBlockChange by choices("S22PacketMultiBlockChange", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS23PacketBlockChange by choices("S23PacketBlockChange", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS24PacketBlockAction by choices("S24PacketBlockAction", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS25PacketBlockBreakAnim by choices("S25PacketBlockBreakAnim", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS26PacketMapChunkBulk by choices("S26PacketMapChunkBulk", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS27PacketExplosion by choices("S27PacketExplosion", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS28PacketEffect by choices("S28PacketEffect", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS29PacketSoundEffect by choices("S29PacketSoundEffect", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS2APacketParticles by choices("S2APacketParticles", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS2BPacketChangeGameState by choices("S2BPacketChangeGameState", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS2CPacketSpawnGlobalEntity by choices("S2CPacketSpawnGlobalEntity", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS2DPacketOpenWindow by choices("S2DPacketOpenWindow", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS2EPacketCloseWindow by choices("S2EPacketCloseWindow", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS2FPacketSetSlot by choices("S2FPacketSetSlot", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS30PacketWindowItems by choices("S30PacketWindowItems", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS31PacketWindowProperty by choices("S31PacketWindowProperty", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS32PacketConfirmTransaction by choices("S32PacketConfirmTransaction", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS33PacketUpdateSign by choices("S33PacketUpdateSign", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS34PacketMaps by choices("S34PacketMaps", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS35PacketUpdateTileEntity by choices("S35PacketUpdateTileEntity", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS36PacketSignEditorOpen by choices("S36PacketSignEditorOpen", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS37PacketStatistics by choices("S37PacketStatistics", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS38PacketPlayerListItem by choices("S38PacketPlayerListItem", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS39PacketPlayerAbilities by choices("S39PacketPlayerAbilities", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS3APacketTabComplete by choices("S3APacketTabComplete", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS3BPacketScoreboardObjective by choices("S3BPacketScoreboardObjective", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS3CPacketUpdateScore by choices("S3CPacketUpdateScore", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS3DPacketDisplayScoreboard by choices("S3DPacketDisplayScoreboard", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS3EPacketTeams by choices("S3EPacketTeams", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS3FPacketCustomPayload by choices("S3FPacketCustomPayload", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS40PacketDisconnect by choices("S40PacketDisconnect", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS41PacketServerDifficulty by choices("S41PacketServerDifficulty", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS42PacketCombatEvent by choices("S42PacketCombatEvent", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS43PacketCamera by choices("S43PacketCamera", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS44PacketWorldBorder by choices("S44PacketWorldBorder", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS45PacketTitle by choices("S45PacketTitle", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS46PacketSetCompressionLevel by choices("S46PacketSetCompressionLevel", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS47PacketPlayerListHeaderFooter by choices("S47PacketPlayerListHeaderFooter", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS48PacketResourcePackSend by choices("S48PacketResourcePackSend", arrayOf("NoControl","Cancel"), "NoControl")
    val ControlS49PacketUpdateEntityNBT by choices("S49PacketUpdateEntityNBT", arrayOf("NoControl","Cancel"), "NoControl")

    // 数据包事件处理器
    val onPacket = handler<PacketEvent> { event ->
        when (event.packet) {
            // 登录协议包 (客户端)
            is C00PacketLoginStart -> if (ControlC00PacketLoginStart == "Cancel") event.cancelEvent()
            is C01PacketEncryptionResponse -> if (ControlC01PacketEncryptionResponse == "Cancel") event.cancelEvent()

            // 状态协议包 (客户端)
            is C00PacketServerQuery -> if (ControlC00PacketServerQuery == "Cancel") event.cancelEvent()
            is C01PacketPing -> if (ControlC01PacketPing == "Cancel") event.cancelEvent()

            // 游戏协议包 (客户端)
            is C00PacketKeepAlive -> if (ControlC00PacketKeepAlive == "Cancel") event.cancelEvent()
            is C01PacketChatMessage -> if (ControlC01PacketChatMessage == "Cancel") event.cancelEvent()
            is C02PacketUseEntity -> if (ControlC02PacketUseEntity == "Cancel") event.cancelEvent()
            is C03PacketPlayer -> if (ControlC03PacketPlayer == "Cancel") event.cancelEvent()
            is C07PacketPlayerDigging -> if (ControlC07PacketPlayerDigging == "Cancel") event.cancelEvent()
            is C08PacketPlayerBlockPlacement -> if (ControlC08PacketPlayerBlockPlacement == "Cancel") event.cancelEvent()
            is C09PacketHeldItemChange -> if (ControlC09PacketHeldItemChange == "Cancel") event.cancelEvent()
            is C0APacketAnimation -> if (ControlC0APacketAnimation == "Cancel") event.cancelEvent()
            is C0BPacketEntityAction -> if (ControlC0BPacketEntityAction == "Cancel") event.cancelEvent()
            is C0CPacketInput -> if (ControlC0CPacketInput == "Cancel") event.cancelEvent()
            is C0DPacketCloseWindow -> if (ControlC0DPacketCloseWindow == "Cancel") event.cancelEvent()
            is C0EPacketClickWindow -> if (ControlC0EPacketClickWindow == "Cancel") event.cancelEvent()
            is C0FPacketConfirmTransaction -> if (ControlC0FPacketConfirmTransaction == "Cancel") event.cancelEvent()
            is C10PacketCreativeInventoryAction -> if (ControlC10PacketCreativeInventoryAction == "Cancel") event.cancelEvent()
            is C11PacketEnchantItem -> if (ControlC11PacketEnchantItem == "Cancel") event.cancelEvent()
            is C12PacketUpdateSign -> if (ControlC12PacketUpdateSign == "Cancel") event.cancelEvent()
            is C13PacketPlayerAbilities -> if (ControlC13PacketPlayerAbilities == "Cancel") event.cancelEvent()
            is C14PacketTabComplete -> if (ControlC14PacketTabComplete == "Cancel") event.cancelEvent()
            is C15PacketClientSettings -> if (ControlC15PacketClientSettings == "Cancel") event.cancelEvent()
            is C16PacketClientStatus -> if (ControlC16PacketClientStatus == "Cancel") event.cancelEvent()
            is C17PacketCustomPayload -> if (ControlC17PacketCustomPayload == "Cancel") event.cancelEvent()
            is C18PacketSpectate -> if (ControlC18PacketSpectate == "Cancel") event.cancelEvent()
            is C19PacketResourcePackStatus -> if (ControlC19PacketResourcePackStatus == "Cancel") event.cancelEvent()

            // 握手协议包 (客户端)
            is C00Handshake -> if (ControlC00Handshake == "Cancel") event.cancelEvent()

            // 登录协议包 (服务端)
            is S00PacketDisconnect -> if (ControlS00PacketDisconnect == "Cancel") event.cancelEvent()
            is S01PacketEncryptionRequest -> if (ControlS01PacketEncryptionRequest == "Cancel") event.cancelEvent()
            is S02PacketLoginSuccess -> if (ControlS02PacketLoginSuccess == "Cancel") event.cancelEvent()
            is S03PacketEnableCompression -> if (ControlS03PacketEnableCompression == "Cancel") event.cancelEvent()

            // 状态协议包 (服务端)
            is S00PacketServerInfo -> if (ControlS00PacketServerInfo == "Cancel") event.cancelEvent()
            is S01PacketPong -> if (ControlS01PacketPong == "Cancel") event.cancelEvent()

            // 游戏协议包 (服务端)
            is S00PacketKeepAlive -> if (ControlS00PacketKeepAlive == "Cancel") event.cancelEvent()
            is S01PacketJoinGame -> if (ControlS01PacketJoinGame == "Cancel") event.cancelEvent()
            is S02PacketChat -> if (ControlS02PacketChat == "Cancel") event.cancelEvent()
            is S03PacketTimeUpdate -> if (ControlS03PacketTimeUpdate == "Cancel") event.cancelEvent()
            is S04PacketEntityEquipment -> if (ControlS04PacketEntityEquipment == "Cancel") event.cancelEvent()
            is S05PacketSpawnPosition -> if (ControlS05PacketSpawnPosition == "Cancel") event.cancelEvent()
            is S06PacketUpdateHealth -> if (ControlS06PacketUpdateHealth == "Cancel") event.cancelEvent()
            is S07PacketRespawn -> if (ControlS07PacketRespawn == "Cancel") event.cancelEvent()
            is S08PacketPlayerPosLook -> if (ControlS08PacketPlayerPosLook == "Cancel") event.cancelEvent()
            is S09PacketHeldItemChange -> if (ControlS09PacketHeldItemChange == "Cancel") event.cancelEvent()
            is S0APacketUseBed -> if (ControlS0APacketUseBed == "Cancel") event.cancelEvent()
            is S0BPacketAnimation -> if (ControlS0BPacketAnimation == "Cancel") event.cancelEvent()
            is S0CPacketSpawnPlayer -> if (ControlS0CPacketSpawnPlayer == "Cancel") event.cancelEvent()
            is S0DPacketCollectItem -> if (ControlS0DPacketCollectItem == "Cancel") event.cancelEvent()
            is S0EPacketSpawnObject -> if (ControlS0EPacketSpawnObject == "Cancel") event.cancelEvent()
            is S0FPacketSpawnMob -> if (ControlS0FPacketSpawnMob == "Cancel") event.cancelEvent()
            is S10PacketSpawnPainting -> if (ControlS10PacketSpawnPainting == "Cancel") event.cancelEvent()
            is S11PacketSpawnExperienceOrb -> if (ControlS11PacketSpawnExperienceOrb == "Cancel") event.cancelEvent()
            is S12PacketEntityVelocity -> if (ControlS12PacketEntityVelocity == "Cancel") event.cancelEvent()
            is S13PacketDestroyEntities -> if (ControlS13PacketDestroyEntities == "Cancel") event.cancelEvent()
            is S14PacketEntity -> if (ControlS14PacketEntity == "Cancel") event.cancelEvent()
            is S18PacketEntityTeleport -> if (ControlS18PacketEntityTeleport == "Cancel") event.cancelEvent()
            is S19PacketEntityHeadLook -> if (ControlS19PacketEntityHeadLook == "Cancel") event.cancelEvent()
            is S19PacketEntityStatus -> if (ControlS19PacketEntityStatus == "Cancel") event.cancelEvent()
            is S1BPacketEntityAttach -> if (ControlS1BPacketEntityAttach == "Cancel") event.cancelEvent()
            is S1CPacketEntityMetadata -> if (ControlS1CPacketEntityMetadata == "Cancel") event.cancelEvent()
            is S1DPacketEntityEffect -> if (ControlS1DPacketEntityEffect == "Cancel") event.cancelEvent()
            is S1EPacketRemoveEntityEffect -> if (ControlS1EPacketRemoveEntityEffect == "Cancel") event.cancelEvent()
            is S1FPacketSetExperience -> if (ControlS1FPacketSetExperience == "Cancel") event.cancelEvent()
            is S20PacketEntityProperties -> if (ControlS20PacketEntityProperties == "Cancel") event.cancelEvent()
            is S21PacketChunkData -> if (ControlS21PacketChunkData == "Cancel") event.cancelEvent()
            is S22PacketMultiBlockChange -> if (ControlS22PacketMultiBlockChange == "Cancel") event.cancelEvent()
            is S23PacketBlockChange -> if (ControlS23PacketBlockChange == "Cancel") event.cancelEvent()
            is S24PacketBlockAction -> if (ControlS24PacketBlockAction == "Cancel") event.cancelEvent()
            is S25PacketBlockBreakAnim -> if (ControlS25PacketBlockBreakAnim == "Cancel") event.cancelEvent()
            is S26PacketMapChunkBulk -> if (ControlS26PacketMapChunkBulk == "Cancel") event.cancelEvent()
            is S27PacketExplosion -> if (ControlS27PacketExplosion == "Cancel") event.cancelEvent()
            is S28PacketEffect -> if (ControlS28PacketEffect == "Cancel") event.cancelEvent()
            is S29PacketSoundEffect -> if (ControlS29PacketSoundEffect == "Cancel") event.cancelEvent()
            is S2APacketParticles -> if (ControlS2APacketParticles == "Cancel") event.cancelEvent()
            is S2BPacketChangeGameState -> if (ControlS2BPacketChangeGameState == "Cancel") event.cancelEvent()
            is S2CPacketSpawnGlobalEntity -> if (ControlS2CPacketSpawnGlobalEntity == "Cancel") event.cancelEvent()
            is S2DPacketOpenWindow -> if (ControlS2DPacketOpenWindow == "Cancel") event.cancelEvent()
            is S2EPacketCloseWindow -> if (ControlS2EPacketCloseWindow == "Cancel") event.cancelEvent()
            is S2FPacketSetSlot -> if (ControlS2FPacketSetSlot == "Cancel") event.cancelEvent()
            is S30PacketWindowItems -> if (ControlS30PacketWindowItems == "Cancel") event.cancelEvent()
            is S31PacketWindowProperty -> if (ControlS31PacketWindowProperty == "Cancel") event.cancelEvent()
            is S32PacketConfirmTransaction -> if (ControlS32PacketConfirmTransaction == "Cancel") event.cancelEvent()
            is S33PacketUpdateSign -> if (ControlS33PacketUpdateSign == "Cancel") event.cancelEvent()
            is S34PacketMaps -> if (ControlS34PacketMaps == "Cancel") event.cancelEvent()
            is S35PacketUpdateTileEntity -> if (ControlS35PacketUpdateTileEntity == "Cancel") event.cancelEvent()
            is S36PacketSignEditorOpen -> if (ControlS36PacketSignEditorOpen == "Cancel") event.cancelEvent()
            is S37PacketStatistics -> if (ControlS37PacketStatistics == "Cancel") event.cancelEvent()
            is S38PacketPlayerListItem -> if (ControlS38PacketPlayerListItem == "Cancel") event.cancelEvent()
            is S39PacketPlayerAbilities -> if (ControlS39PacketPlayerAbilities == "Cancel") event.cancelEvent()
            is S3APacketTabComplete -> if (ControlS3APacketTabComplete == "Cancel") event.cancelEvent()
            is S3BPacketScoreboardObjective -> if (ControlS3BPacketScoreboardObjective == "Cancel") event.cancelEvent()
            is S3CPacketUpdateScore -> if (ControlS3CPacketUpdateScore == "Cancel") event.cancelEvent()
            is S3DPacketDisplayScoreboard -> if (ControlS3DPacketDisplayScoreboard == "Cancel") event.cancelEvent()
            is S3EPacketTeams -> if (ControlS3EPacketTeams == "Cancel") event.cancelEvent()
            is S3FPacketCustomPayload -> if (ControlS3FPacketCustomPayload == "Cancel") event.cancelEvent()
            is S40PacketDisconnect -> if (ControlS40PacketDisconnect == "Cancel") event.cancelEvent()
            is S41PacketServerDifficulty -> if (ControlS41PacketServerDifficulty == "Cancel") event.cancelEvent()
            is S42PacketCombatEvent -> if (ControlS42PacketCombatEvent == "Cancel") event.cancelEvent()
            is S43PacketCamera -> if (ControlS43PacketCamera == "Cancel") event.cancelEvent()
            is S44PacketWorldBorder -> if (ControlS44PacketWorldBorder == "Cancel") event.cancelEvent()
            is S45PacketTitle -> if (ControlS45PacketTitle == "Cancel") event.cancelEvent()
            is S46PacketSetCompressionLevel -> if (ControlS46PacketSetCompressionLevel == "Cancel") event.cancelEvent()
            is S47PacketPlayerListHeaderFooter -> if (ControlS47PacketPlayerListHeaderFooter == "Cancel") event.cancelEvent()
            is S48PacketResourcePackSend -> if (ControlS48PacketResourcePackSend == "Cancel") event.cancelEvent()
            is S49PacketUpdateEntityNBT -> if (ControlS49PacketUpdateEntityNBT == "Cancel") event.cancelEvent()
        }
    }

    val onUpdate = handler<UpdateEvent> { event ->
        // 登录协议包 (客户端)
        if (ControlC00PacketLoginStart == "Send") sendPacket(C00PacketLoginStart(), false)
        if (ControlC01PacketEncryptionResponse == "Send") sendPacket(C01PacketEncryptionResponse(), false)

        // 状态协议包 (客户端)
        if (ControlC00PacketServerQuery == "Send") sendPacket(C00PacketServerQuery(), false)
        if (ControlC01PacketPing == "Send") sendPacket(C01PacketPing(), false)

        // 游戏协议包 (客户端)
        if (ControlC00PacketKeepAlive == "Send") sendPacket(C00PacketKeepAlive(), false)
        if (ControlC01PacketChatMessage == "Send") sendPacket(C01PacketChatMessage(), false)
        if (ControlC02PacketUseEntity == "Send") sendPacket(C02PacketUseEntity(), false)
        if (ControlC03PacketPlayer == "Send") sendPacket(C03PacketPlayer(), false)
        if (ControlC04PacketPlayerPosition == "Send") sendPacket(C03PacketPlayer.C04PacketPlayerPosition(), false)
        if (ControlC05PacketPlayerLook == "Send") sendPacket(C03PacketPlayer.C05PacketPlayerLook(), false)
        if (ControlC06PacketPlayerPosLook == "Send") sendPacket(C03PacketPlayer.C06PacketPlayerPosLook(), false)
        if (ControlC07PacketPlayerDigging == "Send") sendPacket(C07PacketPlayerDigging(), false)
        if (ControlC08PacketPlayerBlockPlacement == "Send") sendPacket(C08PacketPlayerBlockPlacement(), false)
        if (ControlC09PacketHeldItemChange == "Send") sendPacket(C09PacketHeldItemChange(), false)
        if (ControlC0APacketAnimation == "Send") sendPacket(C0APacketAnimation(), false)
        if (ControlC0BPacketEntityAction == "Send") sendPacket(C0BPacketEntityAction(), false)
        if (ControlC0CPacketInput == "Send") sendPacket(C0CPacketInput(), false)
        if (ControlC0DPacketCloseWindow == "Send") sendPacket(C0DPacketCloseWindow(), false)
        if (ControlC0EPacketClickWindow == "Send") sendPacket(C0EPacketClickWindow(), false)
        if (ControlC0FPacketConfirmTransaction == "Send") sendPacket(C0FPacketConfirmTransaction(), false)
        if (ControlC10PacketCreativeInventoryAction == "Send") sendPacket(C10PacketCreativeInventoryAction(), false)
        if (ControlC11PacketEnchantItem == "Send") sendPacket(C11PacketEnchantItem(), false)
        if (ControlC12PacketUpdateSign == "Send") sendPacket(C12PacketUpdateSign(), false)
        if (ControlC13PacketPlayerAbilities == "Send") sendPacket(C13PacketPlayerAbilities(), false)
        if (ControlC14PacketTabComplete == "Send") sendPacket(C14PacketTabComplete(), false)
        if (ControlC15PacketClientSettings == "Send") sendPacket(C15PacketClientSettings(), false)
        if (ControlC16PacketClientStatus == "Send") sendPacket(C16PacketClientStatus(), false)
        if (ControlC17PacketCustomPayload == "Send") sendPacket(C17PacketCustomPayload(), false)
        if (ControlC18PacketSpectate == "Send") sendPacket(C18PacketSpectate(), false)
        if (ControlC19PacketResourcePackStatus == "Send") sendPacket(C19PacketResourcePackStatus(), false)

        // 握手协议包 (客户端)
        if (ControlC00Handshake == "Send") sendPacket(C00Handshake(), false)
    }
}